/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_package;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import javax.swing.JPanel;

/**
 *
 * @author s.palero
 */
public class FirstFrame extends javax.swing.JFrame {

    /**
     * Creates new form FirstFrame
     */
    public FirstFrame() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baybayin_op = new javax.swing.JPanel();
        baybayin1 = new javax.swing.JLabel();
        abakada1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        pilipino1 = new javax.swing.JLabel();
        pilipino2 = new javax.swing.JLabel();
        baybayin2 = new javax.swing.JLabel();
        enter = new javax.swing.JButton();
        pilipino3 = new javax.swing.JLabel();
        pilipino4 = new javax.swing.JLabel();
        pilipino5 = new javax.swing.JLabel();
        pilipino6 = new javax.swing.JLabel();
        pilipino7 = new javax.swing.JLabel();
        baybayin3 = new javax.swing.JLabel();
        baybayin4 = new javax.swing.JLabel();
        baybayin5 = new javax.swing.JLabel();
        baybayin6 = new javax.swing.JLabel();
        pilipino8 = new javax.swing.JLabel();
        baybayin7 = new javax.swing.JLabel();
        baybayin8 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        baybayin_op.setBackground(new java.awt.Color(254, 225, 233));

        baybayin1.setFont(new java.awt.Font("Baybayin Modern Script", 0, 36)); // NOI18N
        baybayin1.setForeground(new java.awt.Color(204, 204, 204));
        baybayin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baybayin1.setText("ating ipagmalaki ang sariling atin");
        baybayin1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        abakada1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        abakada1.setForeground(new java.awt.Color(204, 204, 204));
        abakada1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abakada1.setText("ating ipagmalaki ang sariling atin");
        abakada1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        title.setFont(new java.awt.Font("Lucida Calligraphy", 0, 50)); // NOI18N
        title.setForeground(new java.awt.Color(51, 51, 51));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Baybayin");
        title.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        pilipino1.setFont(new java.awt.Font("Shorelines Script Bold", 0, 24)); // NOI18N
        pilipino1.setForeground(new java.awt.Color(204, 204, 204));
        pilipino1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pilipino1.setText("pilipino");
        pilipino1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        pilipino2.setFont(new java.awt.Font("Shorelines Script Bold", 0, 24)); // NOI18N
        pilipino2.setForeground(new java.awt.Color(153, 153, 153));
        pilipino2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pilipino2.setText("Pilipino");
        pilipino2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        baybayin2.setFont(new java.awt.Font("Baybayin Modern Script", 0, 36)); // NOI18N
        baybayin2.setForeground(new java.awt.Color(204, 204, 204));
        baybayin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baybayin2.setText("pilipino");
        baybayin2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        enter.setBackground(new java.awt.Color(255, 204, 204));
        enter.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        enter.setForeground(new java.awt.Color(102, 102, 102));
        enter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/pics/icons8_diamond_heart_25px.png"))); // NOI18N
        enter.setText("ENTER");
        enter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        enter.setBorderPainted(false);
        enter.setFocusPainted(false);
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        pilipino3.setFont(new java.awt.Font("Shorelines Script Bold", 0, 24)); // NOI18N
        pilipino3.setForeground(new java.awt.Color(153, 153, 153));
        pilipino3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pilipino3.setText("Pilipino");
        pilipino3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        pilipino4.setFont(new java.awt.Font("Shorelines Script Bold", 0, 24)); // NOI18N
        pilipino4.setForeground(new java.awt.Color(204, 204, 204));
        pilipino4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pilipino4.setText("pilipino");
        pilipino4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        pilipino5.setFont(new java.awt.Font("Shorelines Script Bold", 0, 24)); // NOI18N
        pilipino5.setForeground(new java.awt.Color(153, 153, 153));
        pilipino5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pilipino5.setText("Pilipino");
        pilipino5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        pilipino6.setFont(new java.awt.Font("Shorelines Script Bold", 0, 24)); // NOI18N
        pilipino6.setForeground(new java.awt.Color(204, 204, 204));
        pilipino6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pilipino6.setText("pilipino");
        pilipino6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        pilipino7.setFont(new java.awt.Font("Baybayin Modern Script", 0, 36)); // NOI18N
        pilipino7.setForeground(new java.awt.Color(153, 153, 153));
        pilipino7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pilipino7.setText("pilipino");
        pilipino7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        baybayin3.setFont(new java.awt.Font("Baybayin Modern Script", 0, 36)); // NOI18N
        baybayin3.setForeground(new java.awt.Color(204, 204, 204));
        baybayin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baybayin3.setText("pilipino");
        baybayin3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        baybayin4.setFont(new java.awt.Font("Baybayin Modern Script", 0, 36)); // NOI18N
        baybayin4.setForeground(new java.awt.Color(153, 153, 153));
        baybayin4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baybayin4.setText("pilipino");
        baybayin4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        baybayin5.setFont(new java.awt.Font("Baybayin Modern Script", 0, 36)); // NOI18N
        baybayin5.setForeground(new java.awt.Color(204, 204, 204));
        baybayin5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baybayin5.setText("pilipino");
        baybayin5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        baybayin6.setFont(new java.awt.Font("Baybayin Modern Script", 0, 36)); // NOI18N
        baybayin6.setForeground(new java.awt.Color(153, 153, 153));
        baybayin6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baybayin6.setText("pilipino");
        baybayin6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        pilipino8.setFont(new java.awt.Font("Shorelines Script Bold", 0, 24)); // NOI18N
        pilipino8.setForeground(new java.awt.Color(153, 153, 153));
        pilipino8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pilipino8.setText("Pilipino");
        pilipino8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        baybayin7.setFont(new java.awt.Font("Baybayin Modern Script", 0, 36)); // NOI18N
        baybayin7.setForeground(new java.awt.Color(153, 153, 153));
        baybayin7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baybayin7.setText("pilipino");
        baybayin7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        baybayin8.setFont(new java.awt.Font("Baybayin Modern Script", 0, 36)); // NOI18N
        baybayin8.setForeground(new java.awt.Color(204, 204, 204));
        baybayin8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baybayin8.setText("pilipino");
        baybayin8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btn_exit.setBackground(new java.awt.Color(255, 204, 204));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(102, 102, 102));
        btn_exit.setText("X");
        btn_exit.setBorder(null);
        btn_exit.setBorderPainted(false);
        btn_exit.setFocusPainted(false);
        btn_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout baybayin_opLayout = new javax.swing.GroupLayout(baybayin_op);
        baybayin_op.setLayout(baybayin_opLayout);
        baybayin_opLayout.setHorizontalGroup(
            baybayin_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baybayin_opLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(baybayin_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baybayin_opLayout.createSequentialGroup()
                        .addComponent(baybayin1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(baybayin_opLayout.createSequentialGroup()
                        .addGroup(baybayin_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pilipino8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilipino1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilipino5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilipino6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilipino2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilipino3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilipino4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(baybayin_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(baybayin_opLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                                .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(219, 219, 219))
                            .addGroup(baybayin_opLayout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(baybayin_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(baybayin8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baybayin_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(baybayin6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(baybayin2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(baybayin_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(baybayin4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(baybayin5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pilipino7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(baybayin3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(baybayin7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baybayin_opLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(abakada1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        baybayin_opLayout.setVerticalGroup(
            baybayin_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baybayin_opLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(baybayin_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(baybayin_opLayout.createSequentialGroup()
                        .addGroup(baybayin_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(baybayin1)
                            .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pilipino8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilipino1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilipino5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilipino6)
                        .addGroup(baybayin_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(baybayin_opLayout.createSequentialGroup()
                                .addComponent(pilipino3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pilipino4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pilipino2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baybayin_opLayout.createSequentialGroup()
                                .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))))
                    .addGroup(baybayin_opLayout.createSequentialGroup()
                        .addGroup(baybayin_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(baybayin_opLayout.createSequentialGroup()
                                .addComponent(pilipino7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(baybayin3))
                            .addGroup(baybayin_opLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(baybayin_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(title)
                                    .addGroup(baybayin_opLayout.createSequentialGroup()
                                        .addComponent(baybayin4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(baybayin5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(baybayin6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(baybayin2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baybayin7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baybayin8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(abakada1)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baybayin_op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baybayin_op, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void setColor(JPanel panel) {
        panel.setBackground(new Color(254, 219, 219));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(255, 211, 218));
    }
    
    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        SecFrame sf2 = new SecFrame();
        sf2.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(FirstFrame.HIDE_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_enterActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abakada1;
    private javax.swing.JLabel baybayin1;
    private javax.swing.JLabel baybayin2;
    private javax.swing.JLabel baybayin3;
    private javax.swing.JLabel baybayin4;
    private javax.swing.JLabel baybayin5;
    private javax.swing.JLabel baybayin6;
    private javax.swing.JLabel baybayin7;
    private javax.swing.JLabel baybayin8;
    private javax.swing.JPanel baybayin_op;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton enter;
    private javax.swing.JLabel pilipino1;
    private javax.swing.JLabel pilipino2;
    private javax.swing.JLabel pilipino3;
    private javax.swing.JLabel pilipino4;
    private javax.swing.JLabel pilipino5;
    private javax.swing.JLabel pilipino6;
    private javax.swing.JLabel pilipino7;
    private javax.swing.JLabel pilipino8;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
